In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [17]:
df = pd.read_csv('/content/combined_dataframe1 (1).csv')

<ipython-input-17-98fcdf91c762>:1: DtypeWarning: Columns (77,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/combined_dataframe1 (1).csv')

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
df.nunique()

Year                 3
Quarter              4
Month               12
DayofMonth          31
DayOfWeek            7
                    ..
Div5TotalGTime       0
Div5LongestGTime     0
Div5WheelsOff        0
Div5TailNum          0
Unnamed: 109         0
Length: 110, dtype: int64

In [18]:
rows, columns = df.shape

In [21]:
columns

110

In [19]:
df1 = df.copy()

In [20]:
for col in df.columns:
  nan = df[col].isna().sum()
  if nan == rows:
    df1 = df1.drop([col], axis=1)

In [22]:
df1.shape

(548760, 85)

In [23]:
df1.duplicated().sum()

0

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 548760 entries, 0 to 548759
Data columns (total 85 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   Year                             548760 non-null  int64
 1   Quarter                          548760 non-null  int64
 2   Month                            548760 non-null  int64
 3   DayofMonth                       548760 non-null  int64
 4   DayOfWeek                        548760 non-null  int64
 5   FlightDate                       548760 non-null  object
 6   Reporting_Airline                548760 non-null  object
 7   DOT_ID_Reporting_Airline         548760 non-null  int64
 8   IATA_CODE_Reporting_Airline      548760 non-null  object
 9   Tail_Number                      546764 non-null  object
 10  Flight_Number_Reporting_Airline  548760 non-null  int64
 11  OriginAirportID                  548760 non-null  int64
 12  OriginAirportSeqID               548760 non-null  int64
 13  OriginCityMarketID               548760 non-null  int64
 14  Origin                           548760 non-null  object
 15  OriginCityName                   548760 non-null  object
 16  OriginState                      548760 non-null  object
 17  OriginStateFips                  548760 non-null  int64
 18  OriginStateName                  548760 non-null  object
 19  OriginWac                        548760 non-null  int64
 20  DestAirportID                    548760 non-null  int64
 21  DestAirportSeqID                 548760 non-null  int64
 22  DestCityMarketID                 548760 non-null  int64
 23  Dest                             548760 non-null  object
 24  DestCityName                     548760 non-null  object
 25  DestState                        548760 non-null  object
 26  DestStateFips                    548760 non-null  int64
 27  DestStateName                    548760 non-null  object
 28  DestWac                          548760 non-null  int64
 29  CRSDepTime                       548760 non-null  int64
 30  DepTime                          538770 non-null  float64
 31  DepDelay                         538762 non-null  float64
 32  DepDelayMinutes                  538762 non-null  float64
 33  DepDel15                         538762 non-null  float64
 34  DepartureDelayGroups             538762 non-null  float64
 35  DepTimeBlk                       548760 non-null  object
 36  TaxiOut                          538503 non-null  float64
 37  WheelsOff                        538503 non-null  float64
 38  WheelsOn                         538294 non-null  float64
 39  TaxiIn                           538294 non-null  float64
 40  CRSArrTime                       548760 non-null  int64
 41  ArrTime                          538294 non-null  float64
 42  ArrDelay                         537033 non-null  float64
 43  ArrDelayMinutes                  537033 non-null  float64
 44  ArrDel15                         537033 non-null  float64
 45  ArrivalDelayGroups               537033 non-null  float64
 46  ArrTimeBlk                       548760 non-null  object
 47  Cancelled                        548760 non-null  int64
 48  CancellationCode                 10307 non-null   object
 49  Diverted                         548760 non-null  int64
 50  CRSElapsedTime                   548760 non-null  int64
 51  ActualElapsedTime                537033 non-null  float64
 52  AirTime                          537033 non-null  float64
 53  Flights                          548760 non-null  int64
 54  Distance                         548760 non-null  int64
 55  DistanceGroup                    548760 non-null  int64
 56  CarrierDelay                     115300 non-null  float64
 57  WeatherDelay                     115300 non-null  float64
 58  NASDelay                         115300 non-null  float64
 59  SecurityDelay                    115300 non-null  float64
 60  LateAircraftDelay                115300 non-null  float64
 61  FirstDepTime                     3720 non-null    float64
 62  TotalAddGTime                    3720 non-null    float64
 63  LongestAddGTime                  3720 non-null    float64
 64  DivAirportLandings               548760 non-null  int64
 65  DivReachedDest                   1420 non-null    float64
 66  DivActualElapsedTime             1261 non-null    float64
 67  DivArrDelay                      1261 non-null    float64
 68  DivDistance                      1420 non-null    float64
 69  Div1Airport                      1470 non-null    object
 70  Div1AirportID                    1470 non-null    float64
 71  Div1AirportSeqID                 1470 non-null    float64
 72  Div1WheelsOn                     1470 non-null    float64
 73  Div1TotalGTime                   1470 non-null    float64
 74  Div1LongestGTime                 1470 non-null    float64
 75  Div1WheelsOff                    1263 non-null    float64
 76  Div1TailNum                      1263 non-null    object
 77  Div2Airport                      8 non-null       object
 78  Div2AirportID                    8 non-null       float64
 79  Div2AirportSeqID                 8 non-null       float64
 80  Div2WheelsOn                     8 non-null       float64
 81  Div2TotalGTime                   8 non-null       float64
 82  Div2LongestGTime                 8 non-null       float64
 83  Div2WheelsOff                    6 non-null       float64
 84  Div2TailNum                      6 non-null       object
dtypes: float64(40), int64(26), object(19)
memory usage: 355.9+ MB

In [25]:
df1.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum
0,2024,3,7,6,6,7/6/2024,AS,19930,AS,N528AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,3,7,25,4,7/25/2024,WN,19393,WN,N256WN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,3,7,14,7,7/14/2024,DL,19790,DL,N554NW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,3,7,17,3,7/17/2024,DL,19790,DL,N578DN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,3,7,21,7,7/21/2024,AA,19805,AA,N827NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
"""nan_cols = []

for col in df1.columns:
  print(col)
  nan = df[col].isna().sum()
  if nan != 0:
    nan_cols.append(col)
  print([len(df1[col].unique()), nan])
  print('-'*20)"""

"nan_cols = []\n\nfor col in df1.columns:\n  print(col)\n  nan = df[col].isna().sum()\n  if nan != 0:\n    nan_cols.append(col)\n  print([len(df1[col].unique()), nan])\n  print('-'*20)"

In [ ]:
# nan_cols
# df1.shape

In [26]:
for col in df1.columns:
  nan = df1[col].isna().sum()
  if nan > 540000:
    df1 = df1.drop([col], axis=1)

In [27]:
df1.shape

(548760, 62)

In [28]:
nan_cols = []

for col in df1.columns:
  print(col)
  nan = df[col].isna().sum()
  if nan != 0:
    nan_cols.append(col)
  print([len(df1[col].unique()), nan])
  print('-'*20)

Year
[3, 0]
--------------------
Quarter
[4, 0]
--------------------
Month
[12, 0]
--------------------
DayofMonth
[31, 0]
--------------------
DayOfWeek
[7, 0]
--------------------
FlightDate
[974, 0]
--------------------
Reporting_Airline
[17, 0]
--------------------
DOT_ID_Reporting_Airline
[17, 0]
--------------------
IATA_CODE_Reporting_Airline
[17, 0]
--------------------
Tail_Number
[6540, 1996]
--------------------
Flight_Number_Reporting_Airline
[6602, 0]
--------------------
OriginAirportID
[368, 0]
--------------------
OriginAirportSeqID
[423, 0]
--------------------
OriginCityMarketID
[344, 0]
--------------------
Origin
[368, 0]
--------------------
OriginCityName
[362, 0]
--------------------
OriginState
[52, 0]
--------------------
OriginStateFips
[52, 0]
--------------------
OriginStateName
[52, 0]
--------------------
OriginWac
[52, 0]
--------------------
DestAirportID
[369, 0]
--------------------
DestAirportSeqID
[423, 0]
--------------------
DestCityMarketID
[345, 0]
--------------------
Dest
[369, 0]
--------------------
DestCityName
[363, 0]
--------------------
DestState
[53, 0]
--------------------
DestStateFips
[53, 0]
--------------------
DestStateName
[53, 0]
--------------------
DestWac
[53, 0]
--------------------
CRSDepTime
[1310, 0]
--------------------
DepTime
[1424, 9990]
--------------------
DepDelay
[1152, 9998]
--------------------
DepDelayMinutes
[1108, 9998]
--------------------
DepDel15
[3, 9998]
--------------------
DepartureDelayGroups
[16, 9998]
--------------------
DepTimeBlk
[19, 0]
--------------------
TaxiOut
[164, 10257]
--------------------
WheelsOff
[1423, 10257]
--------------------
WheelsOn
[1441, 10466]
--------------------
TaxiIn
[165, 10466]
--------------------
CRSArrTime
[1405, 0]
--------------------
ArrTime
[1441, 10466]
--------------------
ArrDelay
[1191, 11727]
--------------------
ArrDelayMinutes
[1113, 11727]
--------------------
ArrDel15
[3, 11727]
--------------------
ArrivalDelayGroups
[16, 11727]
--------------------
ArrTimeBlk
[19, 0]
--------------------
Cancelled
[2, 0]
--------------------
CancellationCode
[5, 538453]
--------------------
Diverted
[2, 0]
--------------------
CRSElapsedTime
[594, 0]
--------------------
ActualElapsedTime
[647, 11727]
--------------------
AirTime
[621, 11727]
--------------------
Flights
[1, 0]
--------------------
Distance
[1643, 0]
--------------------
DistanceGroup
[11, 0]
--------------------
CarrierDelay
[897, 433460]
--------------------
WeatherDelay
[459, 433460]
--------------------
NASDelay
[405, 433460]
--------------------
SecurityDelay
[95, 433460]
--------------------
LateAircraftDelay
[686, 433460]
--------------------
DivAirportLandings
[4, 0]
--------------------

In [29]:
def is_one_to_one(df, col1, col2):
    mapping_counts = df.groupby(col1)[col2].nunique()
    return (mapping_counts == 1).all()

#print(is_one_to_one(df1, 'OriginState', 'OriginWac'))
#print(is_one_to_one(df1, 'OriginStateFips', 'OriginWac'))
#print(is_one_to_one(df1, 'OriginStateName', 'OriginWac'))
#print(is_one_to_one(df1, 'OriginStateName', 'OriginStateFips'))
#print(is_one_to_one(df1, 'OriginState', 'OriginStateFips'))
#print(is_one_to_one(df1, 'Origin', 'OriginWac'))

In [31]:
df1 = df1.drop(['Reporting_Airline',
                'IATA_CODE_Reporting_Airline',
                'OriginAirportSeqID',
                'OriginCityMarketID',
                'Origin',
                'OriginState',
                'OriginStateName',
                'OriginStateFips',
                'DestAirportSeqID',
                'DestCityMarketID',
                'Dest',
                'DestState',
                'DestStateName',
                'DestStateFips',
                'ArrDelay',
                'ArrDel15',
                'ArrTimeBlk',
                'DepDelay',
                'DepDel15',
                'DepTimeBlk',
                'ArrivalDelayGroups',
                'DistanceGroup',
                'Quarter',
                  'Month',
'DayofMonth',
'DayOfWeek'
                ], axis=1)

In [32]:
df1.shape

(548760, 36)

In [33]:
df1.head().T

,0,1,2,3,4
Year,2024,2024,2024,2024,2024
FlightDate,7/6/2024,7/25/2024,7/14/2024,7/17/2024,7/21/2024
DOT_ID_Reporting_Airline,19930,19393,19790,19790,19805
Tail_Number,N528AS,N256WN,N554NW,N578DN,N827NN
Flight_Number_Reporting_Airline,339,1016,2925,903,2334
OriginAirportID,12892,12266,13931,10397,15304
OriginCityName,"Los Angeles, CA","Houston, TX","Norfolk, VA","Atlanta, GA","Tampa, FL"
OriginWac,91,74,38,34,33
DestAirportID,12264,11292,10397,14747,11298
DestCityName,"Washington, DC","Denver, CO","Atlanta, GA","Seattle, WA","Dallas/Fort Worth, TX"
DestWac,38,82,34,93,74
CRSDepTime,2139,600,1515,2130,1317
DepTime,2129.0,557.0,1525.0,2135.0,1317.0
DepDelayMinutes,0.0,0.0,10.0,5.0,0.0
DepartureDelayGroups,-1.0,-1.0,0.0,0.0,0.0
TaxiOut,31.0,12.0,18.0,16.0,14.0
WheelsOff,2200.0,609.0,1543.0,2151.0,1331.0
WheelsOn,527.0,704.0,1701.0,2338.0,1443.0
TaxiIn,6.0,5.0,13.0,19.0,13.0
CRSArrTime,540,725,1701,2359,1459
ArrTime,533.0,709.0,1714.0,2357.0,1456.0
ArrDelayMinutes,0.0,0.0,13.0,0.0,0.0
Cancelled,0,0,0,0,0
CancellationCode,NaN,NaN,NaN,NaN,NaN
Diverted,0,0,0,0,0
CRSElapsedTime,301,145,106,329,162
ActualElapsedTime,304.0,132.0,109.0,322.0,159.0
AirTime,267.0,115.0,78.0,287.0,132.0
Flights,1,1,1,1,1
Distance,2288,862,516,2182,929
CarrierDelay,NaN,NaN,NaN,NaN,NaN
WeatherDelay,NaN,NaN,NaN,NaN,NaN
NASDelay,NaN,NaN,NaN,NaN,NaN
SecurityDelay,NaN,NaN,NaN,NaN,NaN
LateAircraftDelay,NaN,NaN,NaN,NaN,NaN
DivAirportLandings,0,0,0,0,0

In [34]:
df1['CancellationCode'].unique()

array([nan, 'A', 'C', 'B', 'D'], dtype=object)

In [35]:
df1[df1['ArrDelayMinutes'] == 0.0]['CancellationCode'].isna().all()

True

In [36]:
(df1[df1['ArrDelayMinutes'] == 0.0]['Cancelled'] == 0.0).all()

True

In [37]:
cancellation_code_mapping = {
    np.nan : 0,
    'A' : 1,
    'B' : 2,
    'C' : 3,
    'D' : 4,
}

df1['CancellationCode_encoded'] = df1['CancellationCode'].map(cancellation_code_mapping).fillna(0).astype(int)

In [ ]:
# df1['CancellationCode_encoded'].unique()

In [38]:
df[df['Cancelled'] == 0.0]['CancellationCode'].isna().all()

True

In [39]:
df1 = df1.drop(['Cancelled', 'CancellationCode'], axis=1)

In [40]:
df1.shape

(548760, 35)

In [41]:
print('CATEGORICAL COLUMNS:')
print('-'*30)
for col in df1.columns:
  if df1[col].dtypes == 'object' or df1[col].dtypes == 'bool':
    print(col)
  else:
    pass

CATEGORICAL COLUMNS:
------------------------------
FlightDate
Tail_Number
OriginCityName
DestCityName

In [42]:
#is_one_to_one(df1, 'Tail_Number', 'Div1TailNum')

KeyError: 'Column not found: Div1TailNum'

In [43]:
df2 = df.copy()

In [44]:
df2.shape

(548760, 110)

In [50]:
df1.to_csv('preprocessed_data.csv')